repo_url: https://github.com/JohnnyLopess/Portugol-C
repo_name: Compilador Portugol-C
site_url: https://johnnylopess.github.io/Portugol-C/
site_name: Compilador Portugol-C

nav:
  - Início: index.md
  - Visão Projeto:
      - Projeto: visaoProduto.md
      - Escopo Portugol: escopo.md
      - Sprints: sprints.md 
  - Resultados:
      - Sprint 1: resultados/sprint1.md
      - Sprint 2: resultados/sprint2.md
      - Sprint 3: resultados/sprint3.md
      - Sprint 4: resultados/sprint4.md
      - Sprint 5: resultados/sprint5.md
      - Sprint 6: resultados/sprint6.md
      - Sprint 7: resultados/sprint7.md
      - Sprint 8: resultados/sprint8.md
      - Sprint 9: resultados/sprint9.md

plugins:
  - search:
      lang:
        - pt
        - en

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.top

  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: green
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo escuro

    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo claro

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences