name: Documentation Deploy

on:
  push:
    paths:
      - 'documentação/**'
      - '.github/workflows/docs-deploy.yml'
  pull_request:
    paths:
      - 'documentação/**'
      - '.github/workflows/docs-deploy.yml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          pip install mkdocs mkdocs-material

      - name: Configurar autenticação do Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Construir e fazer deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        run: |
          mkdocs gh-deploy --force -f documentação/mkdocs.yml --remote-name origin --remote-branch gh-pages
